before_script:
  - source /etc/profile
  - GIT_SSL_NO_VERIFY=true git submodule update --init --recursive

stages:
  - test

test27:
  stage: test
  script:
    - pyenv local 2.7.11
    - make test

test3:
  stage: test
  script:
    - pyenv local 3.5.1
    - make test
